### ISSUE TITLE
Capstone: SQL - Warby Parker

### ISSUE THREAD

**Issue by cviddy17** [danielrmac/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ The presentation shows data-driven analysis that is supported in all the answers.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Queries led to proper data and proper insights.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Queries were properly commented. Great job!
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4 Exceeds Expecatations
* _Comment(s):_ Your presentation is wonderful and shows a mastery of both SQL and the results.

 ### Overall Score: 16/16
Excellent presentation! You seem to have a great grasp of SQL, and your presentation was amazing! Great job!

**Comment by danielrmac** [comment]
Thanks!
